# Generated by Django 4.2.4 on 2024-06-23 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_productimage_image1_alter_productimage_image2_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productimage',
            old_name='image1',
            new_name='image',
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='image3',
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='image4',
        ),
    ]
